# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 23:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fkprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
                ('fkuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User-Profile',
                'verbose_name_plural': 'User-Profiles',
            },
        ),
        migrations.RemoveField(
            model_name='userprofiles',
            name='pkprofile',
        ),
        migrations.RemoveField(
            model_name='userprofiles',
            name='pkuser',
        ),
        migrations.DeleteModel(
            name='UserProfiles',
        ),
    ]
