# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 23:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ('id',), 'verbose_name': 'Status', 'verbose_name_plural': 'Statuses'},
        ),
    ]
