# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HaveDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.Department')),
            ],
            options={
                'verbose_name': 'University-Deparment',
                'verbose_name_plural': 'Universities-Departments',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('direcction', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='havedepartment',
            name='uni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.University'),
        ),
    ]
