# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='havedepartment',
            name='dep',
        ),
        migrations.RemoveField(
            model_name='havedepartment',
            name='uni',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='direcction',
            new_name='direction',
        ),
        migrations.DeleteModel(
            name='HaveDepartment',
        ),
    ]
