# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('universities', '0002_auto_20160704_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='fkdepartment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departments.Department'),
            preserve_default=False,
        ),
    ]
