# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 03:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_auto_20160704_0213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='legal_contitution',
            new_name='legal_constitution',
        ),
    ]
